# Generated by Django 4.2.21 on 2025-05-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="nav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("link", models.CharField(max_length=255, verbose_name="导航链接")),
                (
                    "is_http",
                    models.BooleanField(default=False, verbose_name="是否是外部链接"),
                ),
                (
                    "position",
                    models.IntegerField(
                        choices=[(0, "头部导航"), (1, "底部导航")],
                        default=0,
                        verbose_name="导航位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "导航菜单",
                "verbose_name_plural": "导航菜单",
                "db_table": "lf_nav",
            },
        ),
    ]
