# Generated by Django 4.2.21 on 2025-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "image",
                    models.ImageField(
                        upload_to="banner/%Y/%m", verbose_name="轮播图地址"
                    ),
                ),
                ("link", models.CharField(max_length=500, verbose_name="链接地址")),
                ("note", models.CharField(max_length=150, verbose_name="备注信息")),
                (
                    "is_http",
                    models.BooleanField(
                        default=False,
                        help_text="站点链接地址：http://www.baidu.com/book<br>站点链接地址：/book/",
                        verbose_name="是否外部链接",
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播广告",
                "verbose_name_plural": "轮播广告",
                "db_table": "lf_banner",
            },
        ),
    ]
