# Generated by Django 4.2.21 on 2025-07-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseDirection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="方向名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="方向描述"
                    ),
                ),
                (
                    "recomment_home_pot",
                    models.BooleanField(
                        default=False, verbose_name="是否推荐到首页新课栏目"
                    ),
                ),
                (
                    "recomment_home_top",
                    models.BooleanField(
                        default=False, verbose_name="是否推荐到首页必学栏目"
                    ),
                ),
            ],
            options={
                "verbose_name": "学习方向",
                "verbose_name_plural": "学习方向",
                "db_table": "fg_courses_direction",
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="分类描述"
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="category_list",
                        to="courses.coursedirection",
                        verbose_name="学习方向",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程分类",
                "verbose_name_plural": "课程分类",
                "db_table": "fg_course_category",
            },
        ),
    ]
