# Generated by Django 4.2.21 on 2025-07-25 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "course_cover",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="course/cover",
                        verbose_name="封面图片",
                    ),
                ),
                (
                    "course_video",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="course/video",
                        verbose_name="封面视频",
                    ),
                ),
                (
                    "course_type",
                    models.SmallIntegerField(
                        choices=[(0, "付费购买"), (1, "会员专享"), (2, "学位课程")],
                        default=0,
                        verbose_name="付费类型",
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(0, "初级"), (1, "中级"), (2, "高级")],
                        default=1,
                        verbose_name="难度等级",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="详情介绍"),
                ),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="发布日期"),
                ),
                (
                    "period",
                    models.IntegerField(default=7, verbose_name="建议学习周期(day)"),
                ),
                (
                    "attachment_path",
                    models.FileField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        upload_to="",
                        verbose_name="课件路径",
                    ),
                ),
                (
                    "attachment_link",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="课件链接"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "上线"), (1, "下线"), (2, "预上线")],
                        default=0,
                        verbose_name="课程状态",
                    ),
                ),
                ("students", models.IntegerField(default=0, verbose_name="学习人数")),
                ("lessons", models.IntegerField(default=0, verbose_name="总课时数量")),
                (
                    "pub_lessons",
                    models.IntegerField(default=0, verbose_name="已更新课时数量"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="课程原价",
                    ),
                ),
                (
                    "recomment_home_hot",
                    models.BooleanField(
                        default=False, verbose_name="是否推荐到首页新课栏目"
                    ),
                ),
                (
                    "recomment_home_top",
                    models.BooleanField(
                        default=False, verbose_name="是否推荐到首页必学栏目"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="course_list",
                        to="courses.coursecategory",
                        verbose_name="课程分类",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="course_list",
                        to="courses.coursedirection",
                        verbose_name="学习方向",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程信息",
                "verbose_name_plural": "课程信息",
                "db_table": "fg_course_info",
            },
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.SmallIntegerField(default=1, verbose_name="第几章")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="章节介绍"),
                ),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="发布日期"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_list",
                        to="courses.course",
                        verbose_name="课程名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程章节",
                "verbose_name_plural": "课程章节",
                "db_table": "fg_course_chapter",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orders", models.IntegerField(default=0, verbose_name="显示顺序")),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                (
                    "role",
                    models.SmallIntegerField(
                        choices=[(0, "讲师"), (1, "导师"), (2, "班主任")],
                        default=0,
                        verbose_name="讲师身份",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="职位、职称")),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="导师签名"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        null=True, upload_to="teacher", verbose_name="讲师头像"
                    ),
                ),
                ("brief", models.TextField(max_length=1024, verbose_name="讲师描述")),
            ],
            options={
                "verbose_name": "讲师信息",
                "verbose_name_plural": "讲师信息",
                "db_table": "fg_teacher",
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="标题/名称"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否默认被删除"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
                ("orders", models.SmallIntegerField(default=1, verbose_name="第几节")),
                (
                    "lesson_type",
                    models.SmallIntegerField(
                        choices=[(0, "文档"), (1, "练习"), (2, "视频")],
                        default=2,
                        verbose_name="课时种类",
                    ),
                ),
                (
                    "lesson_link",
                    models.CharField(
                        blank=True,
                        help_text="若是video，填视频地址或者视频id，若是文档，填文档地址",
                        max_length=255,
                        null=True,
                        verbose_name="课时链接",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="课时时长"
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                (
                    "free_trail",
                    models.BooleanField(default=False, verbose_name="是否可试看"),
                ),
                (
                    "recomment",
                    models.BooleanField(
                        default=False, verbose_name="是否推荐到课程列表"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_list",
                        to="courses.coursechapter",
                        verbose_name="章节",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lesson_list",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程课时",
                "verbose_name_plural": "课程课时",
                "db_table": "fg_course_lesson",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_list",
                to="courses.teacher",
                verbose_name="授课老师",
            ),
        ),
    ]
