'''一般用到的常量配置'''
#导航位置对应数字 和 导航条显示大小
NAV_HEADER_POSITION=0
NAV_FOOTER_POSITION=1
NAV_HEADER_SIZE=5
NAV_FOOTER_SIZE=10

#轮播图对应数字
BANNER_POSITION=0
BANNER_SIZE=5

#页面缓存周期
LIST_PAGE_CACHE_TIME=60*60*24

#默认头像
DEFAULT_USER_AVATAR='avatar/2025/avatar2.png'